// Generated by gencpp from file ros_actor_cmd_pose_plugin_msgs/ActorMotion.msg
// DO NOT EDIT!


#ifndef ROS_ACTOR_CMD_POSE_PLUGIN_MSGS_MESSAGE_ACTORMOTION_H
#define ROS_ACTOR_CMD_POSE_PLUGIN_MSGS_MESSAGE_ACTORMOTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_actor_cmd_pose_plugin_msgs
{
template <class ContainerAllocator>
struct ActorMotion_
{
  typedef ActorMotion_<ContainerAllocator> Type;

  ActorMotion_()
    : x(0.0)
    , y(0.0)
    , v(0.0)  {
    }
  ActorMotion_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , v(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _v_type;
  _v_type v;





  typedef boost::shared_ptr< ::ros_actor_cmd_pose_plugin_msgs::ActorMotion_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_actor_cmd_pose_plugin_msgs::ActorMotion_<ContainerAllocator> const> ConstPtr;

}; // struct ActorMotion_

typedef ::ros_actor_cmd_pose_plugin_msgs::ActorMotion_<std::allocator<void> > ActorMotion;

typedef boost::shared_ptr< ::ros_actor_cmd_pose_plugin_msgs::ActorMotion > ActorMotionPtr;
typedef boost::shared_ptr< ::ros_actor_cmd_pose_plugin_msgs::ActorMotion const> ActorMotionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_actor_cmd_pose_plugin_msgs::ActorMotion_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_actor_cmd_pose_plugin_msgs::ActorMotion_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_actor_cmd_pose_plugin_msgs::ActorMotion_<ContainerAllocator1> & lhs, const ::ros_actor_cmd_pose_plugin_msgs::ActorMotion_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.v == rhs.v;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_actor_cmd_pose_plugin_msgs::ActorMotion_<ContainerAllocator1> & lhs, const ::ros_actor_cmd_pose_plugin_msgs::ActorMotion_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_actor_cmd_pose_plugin_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_actor_cmd_pose_plugin_msgs::ActorMotion_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_actor_cmd_pose_plugin_msgs::ActorMotion_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_actor_cmd_pose_plugin_msgs::ActorMotion_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_actor_cmd_pose_plugin_msgs::ActorMotion_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_actor_cmd_pose_plugin_msgs::ActorMotion_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_actor_cmd_pose_plugin_msgs::ActorMotion_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_actor_cmd_pose_plugin_msgs::ActorMotion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bb7c7d549e381f8adcd75ca71e9d210e";
  }

  static const char* value(const ::ros_actor_cmd_pose_plugin_msgs::ActorMotion_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbb7c7d549e381f8aULL;
  static const uint64_t static_value2 = 0xdcd75ca71e9d210eULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_actor_cmd_pose_plugin_msgs::ActorMotion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_actor_cmd_pose_plugin_msgs/ActorMotion";
  }

  static const char* value(const ::ros_actor_cmd_pose_plugin_msgs::ActorMotion_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_actor_cmd_pose_plugin_msgs::ActorMotion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 v\n"
;
  }

  static const char* value(const ::ros_actor_cmd_pose_plugin_msgs::ActorMotion_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_actor_cmd_pose_plugin_msgs::ActorMotion_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.v);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ActorMotion_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_actor_cmd_pose_plugin_msgs::ActorMotion_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_actor_cmd_pose_plugin_msgs::ActorMotion_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "v: ";
    Printer<float>::stream(s, indent + "  ", v.v);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_ACTOR_CMD_POSE_PLUGIN_MSGS_MESSAGE_ACTORMOTION_H
