// Generated by gencpp from file ros_actor_cmd_pose_plugin_msgs/ActorInfo.msg
// DO NOT EDIT!


#ifndef ROS_ACTOR_CMD_POSE_PLUGIN_MSGS_MESSAGE_ACTORINFO_H
#define ROS_ACTOR_CMD_POSE_PLUGIN_MSGS_MESSAGE_ACTORINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_actor_cmd_pose_plugin_msgs
{
template <class ContainerAllocator>
struct ActorInfo_
{
  typedef ActorInfo_<ContainerAllocator> Type;

  ActorInfo_()
    : cls()
    , x(0.0)
    , y(0.0)  {
    }
  ActorInfo_(const ContainerAllocator& _alloc)
    : cls(_alloc)
    , x(0.0)
    , y(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _cls_type;
  _cls_type cls;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::ros_actor_cmd_pose_plugin_msgs::ActorInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_actor_cmd_pose_plugin_msgs::ActorInfo_<ContainerAllocator> const> ConstPtr;

}; // struct ActorInfo_

typedef ::ros_actor_cmd_pose_plugin_msgs::ActorInfo_<std::allocator<void> > ActorInfo;

typedef boost::shared_ptr< ::ros_actor_cmd_pose_plugin_msgs::ActorInfo > ActorInfoPtr;
typedef boost::shared_ptr< ::ros_actor_cmd_pose_plugin_msgs::ActorInfo const> ActorInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_actor_cmd_pose_plugin_msgs::ActorInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_actor_cmd_pose_plugin_msgs::ActorInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_actor_cmd_pose_plugin_msgs::ActorInfo_<ContainerAllocator1> & lhs, const ::ros_actor_cmd_pose_plugin_msgs::ActorInfo_<ContainerAllocator2> & rhs)
{
  return lhs.cls == rhs.cls &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_actor_cmd_pose_plugin_msgs::ActorInfo_<ContainerAllocator1> & lhs, const ::ros_actor_cmd_pose_plugin_msgs::ActorInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_actor_cmd_pose_plugin_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_actor_cmd_pose_plugin_msgs::ActorInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_actor_cmd_pose_plugin_msgs::ActorInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_actor_cmd_pose_plugin_msgs::ActorInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_actor_cmd_pose_plugin_msgs::ActorInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_actor_cmd_pose_plugin_msgs::ActorInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_actor_cmd_pose_plugin_msgs::ActorInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_actor_cmd_pose_plugin_msgs::ActorInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d57df6c0908e158da5273b4646f729dd";
  }

  static const char* value(const ::ros_actor_cmd_pose_plugin_msgs::ActorInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd57df6c0908e158dULL;
  static const uint64_t static_value2 = 0xa5273b4646f729ddULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_actor_cmd_pose_plugin_msgs::ActorInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_actor_cmd_pose_plugin_msgs/ActorInfo";
  }

  static const char* value(const ::ros_actor_cmd_pose_plugin_msgs::ActorInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_actor_cmd_pose_plugin_msgs::ActorInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string cls\n"
"float32 x\n"
"float32 y\n"
;
  }

  static const char* value(const ::ros_actor_cmd_pose_plugin_msgs::ActorInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_actor_cmd_pose_plugin_msgs::ActorInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cls);
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ActorInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_actor_cmd_pose_plugin_msgs::ActorInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_actor_cmd_pose_plugin_msgs::ActorInfo_<ContainerAllocator>& v)
  {
    s << indent << "cls: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.cls);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_ACTOR_CMD_POSE_PLUGIN_MSGS_MESSAGE_ACTORINFO_H
