// Generated by gencpp from file ros_actor_cmd_pose_plugin_msgs/ToggleActorWavingResponse.msg
// DO NOT EDIT!


#ifndef ROS_ACTOR_CMD_POSE_PLUGIN_MSGS_MESSAGE_TOGGLEACTORWAVINGRESPONSE_H
#define ROS_ACTOR_CMD_POSE_PLUGIN_MSGS_MESSAGE_TOGGLEACTORWAVINGRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_actor_cmd_pose_plugin_msgs
{
template <class ContainerAllocator>
struct ToggleActorWavingResponse_
{
  typedef ToggleActorWavingResponse_<ContainerAllocator> Type;

  ToggleActorWavingResponse_()
    : exit(false)  {
    }
  ToggleActorWavingResponse_(const ContainerAllocator& _alloc)
    : exit(false)  {
  (void)_alloc;
    }



   typedef uint8_t _exit_type;
  _exit_type exit;





  typedef boost::shared_ptr< ::ros_actor_cmd_pose_plugin_msgs::ToggleActorWavingResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_actor_cmd_pose_plugin_msgs::ToggleActorWavingResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ToggleActorWavingResponse_

typedef ::ros_actor_cmd_pose_plugin_msgs::ToggleActorWavingResponse_<std::allocator<void> > ToggleActorWavingResponse;

typedef boost::shared_ptr< ::ros_actor_cmd_pose_plugin_msgs::ToggleActorWavingResponse > ToggleActorWavingResponsePtr;
typedef boost::shared_ptr< ::ros_actor_cmd_pose_plugin_msgs::ToggleActorWavingResponse const> ToggleActorWavingResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_actor_cmd_pose_plugin_msgs::ToggleActorWavingResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_actor_cmd_pose_plugin_msgs::ToggleActorWavingResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_actor_cmd_pose_plugin_msgs::ToggleActorWavingResponse_<ContainerAllocator1> & lhs, const ::ros_actor_cmd_pose_plugin_msgs::ToggleActorWavingResponse_<ContainerAllocator2> & rhs)
{
  return lhs.exit == rhs.exit;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_actor_cmd_pose_plugin_msgs::ToggleActorWavingResponse_<ContainerAllocator1> & lhs, const ::ros_actor_cmd_pose_plugin_msgs::ToggleActorWavingResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_actor_cmd_pose_plugin_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_actor_cmd_pose_plugin_msgs::ToggleActorWavingResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_actor_cmd_pose_plugin_msgs::ToggleActorWavingResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_actor_cmd_pose_plugin_msgs::ToggleActorWavingResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_actor_cmd_pose_plugin_msgs::ToggleActorWavingResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_actor_cmd_pose_plugin_msgs::ToggleActorWavingResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_actor_cmd_pose_plugin_msgs::ToggleActorWavingResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_actor_cmd_pose_plugin_msgs::ToggleActorWavingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "36adc7ec869aab8fa937f81c2172ba31";
  }

  static const char* value(const ::ros_actor_cmd_pose_plugin_msgs::ToggleActorWavingResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x36adc7ec869aab8fULL;
  static const uint64_t static_value2 = 0xa937f81c2172ba31ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_actor_cmd_pose_plugin_msgs::ToggleActorWavingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_actor_cmd_pose_plugin_msgs/ToggleActorWavingResponse";
  }

  static const char* value(const ::ros_actor_cmd_pose_plugin_msgs::ToggleActorWavingResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_actor_cmd_pose_plugin_msgs::ToggleActorWavingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool exit\n"
"\n"
;
  }

  static const char* value(const ::ros_actor_cmd_pose_plugin_msgs::ToggleActorWavingResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_actor_cmd_pose_plugin_msgs::ToggleActorWavingResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.exit);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ToggleActorWavingResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_actor_cmd_pose_plugin_msgs::ToggleActorWavingResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_actor_cmd_pose_plugin_msgs::ToggleActorWavingResponse_<ContainerAllocator>& v)
  {
    s << indent << "exit: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.exit);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_ACTOR_CMD_POSE_PLUGIN_MSGS_MESSAGE_TOGGLEACTORWAVINGRESPONSE_H
